language: php
#php:
#  - 5.5
#  - 5.4
#  - hhvm
script: phpunit Test.php

deploy:
  - provider: s3
    access_key_id: ASIAJVWLSBQ5BGGK5FDA 
    secret_access_key: L/zkY14mU882MbE5QUhldL91ph6NyNJCQ7fcArV9  
     # secure: 
    skip_cleanup: true
    on: &2
     # repo: travis-ci/cat-party
    bucket: santed-s3 
#  - provider: codedeploy
#    access_key_id: ASIAJVWLSBQ5BGGK5FDA 
#    secret_access_key: L/zkY14mU882MbE5QUhldL91ph6NyNJCQ7fcArV9
#    bucket: santed-s3 
#    key: santed-latest.zip
#    bundle_type: zip
#    application: santed-cicd-test
#    deployment_group: santed-depGroup-test 
#    on: *2
